# Generated by Django 4.2.6 on 2025-12-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_department_product_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
